//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITFIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classification
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<int> GradeId { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Grade Grade { get; set; }
        public virtual User User { get; set; }

        public override string ToString()
        {
            string grade = "";
            switch (GradeId)
            {
                case 1:
                    grade = "A";
                    break;
                case 2:
                    grade = "B";
                    break;
                case 3:
                    grade = "C";
                    break;
                case 4:
                    grade = "D";
                    break;
                case 5:
                    grade = "E";
                    break;
                case 6:
                    grade = "F";
                    break;
            }
            return grade;
        }
    }
}
