//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITFIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int Id { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual User User { get; set; }

        public static bool operator ==(Registration a, Registration b)
        {
            return ((a.CourseId == b.CourseId) && (a.UserId == b.UserId));
        }

        public static bool operator !=(Registration a, Registration b)
        {
            return ((a.CourseId != b.CourseId) && (a.UserId != b.UserId));
        }
    }
}
